//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Recursos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Campaña.
        /// </summary>
        internal static string AccountsInCampaign {
            get {
                return ResourceManager.GetString("AccountsInCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La acción se ha realizado con éxito.
        /// </summary>
        internal static string ActionCompleted {
            get {
                return ResourceManager.GetString("ActionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activa.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string Active1 {
            get {
                return ResourceManager.GetString("Active1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Activas.
        /// </summary>
        internal static string ActiveAccounts {
            get {
                return ResourceManager.GetString("ActiveAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Activas en la Campaña.
        /// </summary>
        internal static string ActiveAccountsInTheCampaign {
            get {
                return ResourceManager.GetString("ActiveAccountsInTheCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividades de Supervisor.
        /// </summary>
        internal static string ActivityForSupervisors {
            get {
                return ResourceManager.GetString("ActivityForSupervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto a Recaudar.
        /// </summary>
        internal static string Amount_Collect {
            get {
                return ResourceManager.GetString("Amount_Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procede.
        /// </summary>
        internal static string Applicable {
            get {
                return ResourceManager.GetString("Applicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar.
        /// </summary>
        internal static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Asignadas.
        /// </summary>
        internal static string AssignedAccounts {
            get {
                return ResourceManager.GetString("AssignedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operador Asignado.
        /// </summary>
        internal static string AssignedOperator {
            get {
                return ResourceManager.GetString("AssignedOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas Asignadas.
        /// </summary>
        internal static string AssignedPersons {
            get {
                return ResourceManager.GetString("AssignedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Asignación.
        /// </summary>
        internal static string AssignmentDate {
            get {
                return ResourceManager.GetString("AssignmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Operador.
        /// </summary>
        internal static string AssignOperator {
            get {
                return ResourceManager.GetString("AssignOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar a Persona.
        /// </summary>
        internal static string AssignPerson {
            get {
                return ResourceManager.GetString("AssignPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar a Campaña.
        /// </summary>
        internal static string AssignToCampaign {
            get {
                return ResourceManager.GetString("AssignToCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión Asociada.
        /// </summary>
        internal static string Associated_Management {
            get {
                return ResourceManager.GetString("Associated_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntos.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntar Correo Original.
        /// </summary>
        internal static string AttachOriginalEmail {
            get {
                return ResourceManager.GetString("AttachOriginalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación Automática.
        /// </summary>
        internal static string AutomaticAssignment {
            get {
                return ResourceManager.GetString("AutomaticAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Automática de Cuentas a Operadores.
        /// </summary>
        internal static string AutomaticDistributionOfAccountsOperators {
            get {
                return ResourceManager.GetString("AutomaticDistributionOfAccountsOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Automática de cuentas a Campañas.
        /// </summary>
        internal static string AutomaticDistributionOfAccountsToCampaign {
            get {
                return ResourceManager.GetString("AutomaticDistributionOfAccountsToCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Automática de cuentas a Operadores.
        /// </summary>
        internal static string AutomaticDistributionOfAccountsToOperators {
            get {
                return ResourceManager.GetString("AutomaticDistributionOfAccountsToOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Gestión.
        /// </summary>
        internal static string BeginManagement {
            get {
                return ResourceManager.GetString("BeginManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llamada.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llamadas.
        /// </summary>
        internal static string Calls {
            get {
                return ResourceManager.GetString("Calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campaña.
        /// </summary>
        internal static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campañas de Gestión.
        /// </summary>
        internal static string CampaignManagement {
            get {
                return ResourceManager.GetString("CampaignManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campañas.
        /// </summary>
        internal static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas de la campaña.
        /// </summary>
        internal static string CampaignStatistics {
            get {
                return ResourceManager.GetString("CampaignStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Cancelación.
        /// </summary>
        internal static string CancelationDate {
            get {
                return ResourceManager.GetString("CancelationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        internal static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reclamo.
        /// </summary>
        internal static string Claim {
            get {
                return ResourceManager.GetString("Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reclamos.
        /// </summary>
        internal static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasificados pero no leídos.
        /// </summary>
        internal static string ClassifiedButNotRead {
            get {
                return ResourceManager.GetString("ClassifiedButNotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Cliente.
        /// </summary>
        internal static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobrado.
        /// </summary>
        internal static string Collected {
            get {
                return ResourceManager.GetString("Collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compromisos.
        /// </summary>
        internal static string Commitments {
            get {
                return ResourceManager.GetString("Commitments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        internal static string Consult {
            get {
                return ResourceManager.GetString("Consult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Nuevo Aviso.
        /// </summary>
        internal static string CreateNewNotice {
            get {
                return ResourceManager.GetString("CreateNewNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Regla.
        /// </summary>
        internal static string CreateRule {
            get {
                return ResourceManager.GetString("CreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Creación.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creador.
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corriente.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión Actual.
        /// </summary>
        internal static string CurrentManagement {
            get {
                return ResourceManager.GetString("CurrentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicadores.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Desde.
        /// </summary>
        internal static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Hasta.
        /// </summary>
        internal static string DateUntil {
            get {
                return ResourceManager.GetString("DateUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de Entrega.
        /// </summary>
        internal static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Entrega.
        /// </summary>
        internal static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depósito.
        /// </summary>
        internal static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseño de Plantilla.
        /// </summary>
        internal static string DesignTemplate {
            get {
                return ResourceManager.GetString("DesignTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Egreso.
        /// </summary>
        internal static string DischargeDate {
            get {
                return ResourceManager.GetString("DischargeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución.
        /// </summary>
        internal static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haga una Búsqueda para mostrar datos ....
        /// </summary>
        internal static string DoASearchToDisplayData {
            get {
                return ResourceManager.GetString("DoASearchToDisplayData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Inactivas en la Campaña.
        /// </summary>
        internal static string DormantAccountsInCampaign {
            get {
                return ResourceManager.GetString("DormantAccountsInCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración Efectiva.
        /// </summary>
        internal static string EffectiveDuration {
            get {
                return ResourceManager.GetString("EffectiveDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectividad.
        /// </summary>
        internal static string Effectiveness {
            get {
                return ResourceManager.GetString("Effectiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firma de Correos.
        /// </summary>
        internal static string EmailSignature {
            get {
                return ResourceManager.GetString("EmailSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Fin.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar Gestión.
        /// </summary>
        internal static string EndManagement {
            get {
                return ResourceManager.GetString("EndManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Estimada Fin.
        /// </summary>
        internal static string EstimatedEndDate {
            get {
                return ResourceManager.GetString("EstimatedEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasa de Cambio.
        /// </summary>
        internal static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excluir de otras Campañas al asignar a esta.
        /// </summary>
        internal static string ExcludeOtherCampaignsToAssignToThis {
            get {
                return ResourceManager.GetString("ExcludeOtherCampaignsToAssignToThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exclusiones.
        /// </summary>
        internal static string Exclusions {
            get {
                return ResourceManager.GetString("Exclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutar.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extensión.
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo:.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo desde el equipo.
        /// </summary>
        internal static string FileFromPC {
            get {
                return ResourceManager.GetString("FileFromPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flujo.
        /// </summary>
        internal static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flujos.
        /// </summary>
        internal static string Flows {
            get {
                return ResourceManager.GetString("Flows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar.
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión libre.
        /// </summary>
        internal static string FreeManagement {
            get {
                return ResourceManager.GetString("FreeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes Generales.
        /// </summary>
        internal static string GeneralReports {
            get {
                return ResourceManager.GetString("GeneralReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meta.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metas.
        /// </summary>
        internal static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metas Establecidas.
        /// </summary>
        internal static string Goalsset {
            get {
                return ResourceManager.GetString("Goalsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de Inactividad.
        /// </summary>
        internal static string Idle_Time {
            get {
                return ResourceManager.GetString("Idle_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Inactivas.
        /// </summary>
        internal static string InactiveAccounts {
            get {
                return ResourceManager.GetString("InactiveAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bandeja de Entrada.
        /// </summary>
        internal static string InBox {
            get {
                return ResourceManager.GetString("InBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador.
        /// </summary>
        internal static string Indicator {
            get {
                return ResourceManager.GetString("Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicadores.
        /// </summary>
        internal static string Indicators {
            get {
                return ResourceManager.GetString("Indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Ingreso.
        /// </summary>
        internal static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última Gestión.
        /// </summary>
        internal static string LastManagement {
            get {
                return ResourceManager.GetString("LastManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último Operador.
        /// </summary>
        internal static string LastOperator {
            get {
                return ResourceManager.GetString("LastOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado.
        /// </summary>
        internal static string Listing {
            get {
                return ResourceManager.GetString("Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Cuentas sin Asignar.
        /// </summary>
        internal static string ListOfUnallocatedAccounts {
            get {
                return ResourceManager.GetString("ListOfUnallocatedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;120.
        /// </summary>
        internal static string M120 {
            get {
                return ResourceManager.GetString("M120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;180.
        /// </summary>
        internal static string M180 {
            get {
                return ResourceManager.GetString("M180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;30.
        /// </summary>
        internal static string M30 {
            get {
                return ResourceManager.GetString("M30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;45.
        /// </summary>
        internal static string M45 {
            get {
                return ResourceManager.GetString("M45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;60.
        /// </summary>
        internal static string M60 {
            get {
                return ResourceManager.GetString("M60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;90.
        /// </summary>
        internal static string M90 {
            get {
                return ResourceManager.GetString("M90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntar.
        /// </summary>
        internal static string MailAttach {
            get {
                return ResourceManager.GetString("MailAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CCO.
        /// </summary>
        internal static string MailBCC {
            get {
                return ResourceManager.GetString("MailBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CC.
        /// </summary>
        internal static string MailCC {
            get {
                return ResourceManager.GetString("MailCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De.
        /// </summary>
        internal static string MailFrom {
            get {
                return ResourceManager.GetString("MailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correos del Administrador.
        /// </summary>
        internal static string MailFromAdministrator {
            get {
                return ResourceManager.GetString("MailFromAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leído.
        /// </summary>
        internal static string MailRead {
            get {
                return ResourceManager.GetString("MailRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A.
        /// </summary>
        internal static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionado.
        /// </summary>
        internal static string Managed {
            get {
                return ResourceManager.GetString("Managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de Gestión.
        /// </summary>
        internal static string ManagementHistory {
            get {
                return ResourceManager.GetString("ManagementHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestiones.
        /// </summary>
        internal static string Managements {
            get {
                return ResourceManager.GetString("Managements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestiones del Día:.
        /// </summary>
        internal static string ManagementsOfTheDay {
            get {
                return ResourceManager.GetString("ManagementsOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestiones por Semana:.
        /// </summary>
        internal static string ManagementsPerWeek {
            get {
                return ResourceManager.GetString("ManagementsPerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestiones por día.
        /// </summary>
        internal static string Managements_Day {
            get {
                return ResourceManager.GetString("Managements_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar Como Personal.
        /// </summary>
        internal static string MarkAsPersonal {
            get {
                return ResourceManager.GetString("MarkAsPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error guardando la gestión.
        /// </summary>
        internal static string msgErrorManagement {
            get {
                return ResourceManager.GetString("msgErrorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted tiene # Avisos vencidos.
        /// </summary>
        internal static string msgExpiredReminders {
            get {
                return ResourceManager.GetString("msgExpiredReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los correos han sido asignados a la persona satisfactoriamente.
        /// </summary>
        internal static string msgMailAssigned {
            get {
                return ResourceManager.GetString("msgMailAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar una descripción.
        /// </summary>
        internal static string msgMustEnterDescription {
            get {
                return ResourceManager.GetString("msgMustEnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar una referencia.
        /// </summary>
        internal static string msgMustEnterReference {
            get {
                return ResourceManager.GetString("msgMustEnterReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Seleccionar una persona.
        /// </summary>
        internal static string msgMustSelectPerson {
            get {
                return ResourceManager.GetString("msgMustSelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay bancos registrados para este país, por favor avise al dpto de sistemas para solventar esta situación.
        /// </summary>
        internal static string msgNoBanks {
            get {
                return ResourceManager.GetString("msgNoBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha seleccionado ninguna persona para gestionar.
        /// </summary>
        internal static string msgNoPerSel {
            get {
                return ResourceManager.GetString("msgNoPerSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay items en los que el monto del pago excede el monto de la deuda.
        /// </summary>
        internal static string msgPaymentExceedDebt {
            get {
                return ResourceManager.GetString("msgPaymentExceedDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pago se guardó correctamente, Recuerde que lleva unos minutos el procesamiento del mismo..
        /// </summary>
        internal static string msgPaymentSaved {
            get {
                return ResourceManager.GetString("msgPaymentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El monto del pago es menor que la aplicación, si va a hacer un pago parcial, favor editar el monto de la(s) factura(s).
        /// </summary>
        internal static string msgPaymentsDiffersTotal {
            get {
                return ResourceManager.GetString("msgPaymentsDiffersTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pago no se guardó.
        /// </summary>
        internal static string msgPaymentWasntSaved {
            get {
                return ResourceManager.GetString("msgPaymentWasntSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe asignar una fecha de ingreso..
        /// </summary>
        internal static string msgvalidatedate {
            get {
                return ResourceManager.GetString("msgvalidatedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TMO.
        /// </summary>
        internal static string MTO {
            get {
                return ResourceManager.GetString("MTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negativo.
        /// </summary>
        internal static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negativas.
        /// </summary>
        internal static string Negatives {
            get {
                return ResourceManager.GetString("Negatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        internal static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutrales.
        /// </summary>
        internal static string Neutrals {
            get {
                return ResourceManager.GetString("Neutrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Campaña.
        /// </summary>
        internal static string NewCampaign {
            get {
                return ResourceManager.GetString("NewCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Gestión.
        /// </summary>
        internal static string NewManagement {
            get {
                return ResourceManager.GetString("NewManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Operador.
        /// </summary>
        internal static string NewOperator {
            get {
                return ResourceManager.GetString("NewOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Pago.
        /// </summary>
        internal static string NewPayment {
            get {
                return ResourceManager.GetString("NewPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Recordatorio.
        /// </summary>
        internal static string NewReminder {
            get {
                return ResourceManager.GetString("NewReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Regla.
        /// </summary>
        internal static string NewRule {
            get {
                return ResourceManager.GetString("NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Plantilla.
        /// </summary>
        internal static string NewTemplate {
            get {
                return ResourceManager.GetString("NewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Gestionado.
        /// </summary>
        internal static string NoManaged {
            get {
                return ResourceManager.GetString("NoManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Asignar.
        /// </summary>
        internal static string NotAssign {
            get {
                return ResourceManager.GetString("NotAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avisos.
        /// </summary>
        internal static string Notices {
            get {
                return ResourceManager.GetString("Notices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observacion.
        /// </summary>
        internal static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        internal static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abierto.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operaciones.
        /// </summary>
        internal static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operaciones de la Campaña.
        /// </summary>
        internal static string OperationsOfTheCampaign {
            get {
                return ResourceManager.GetString("OperationsOfTheCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operador.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operadores.
        /// </summary>
        internal static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operadores Asignados a la Campaña.
        /// </summary>
        internal static string OperatorsAssignedToCampaign {
            get {
                return ResourceManager.GetString("OperatorsAssignedToCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operadores que me Pueden Suplantar.
        /// </summary>
        internal static string OperatorsThatCanImpersonateMe {
            get {
                return ResourceManager.GetString("OperatorsThatCanImpersonateMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operadores que Puedo Suplantar.
        /// </summary>
        internal static string OperatorsThatICanImpersonate {
            get {
                return ResourceManager.GetString("OperatorsThatICanImpersonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operadores bajo Supervisión.
        /// </summary>
        internal static string OperatorsUnderSupervision {
            get {
                return ResourceManager.GetString("OperatorsUnderSupervision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Original.
        /// </summary>
        internal static string OriginalDate {
            get {
                return ResourceManager.GetString("OriginalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Original.
        /// </summary>
        internal static string OriginalEmail {
            get {
                return ResourceManager.GetString("OriginalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otras Actividades.
        /// </summary>
        internal static string OtherActivities {
            get {
                return ResourceManager.GetString("OtherActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Análisis de Antigüedad.
        /// </summary>
        internal static string OutstandingAccounts {
            get {
                return ResourceManager.GetString("OutstandingAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antigüedad(Dias).
        /// </summary>
        internal static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dueño.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Efectivo.
        /// </summary>
        internal static string PaymentCash {
            get {
                return ResourceManager.GetString("PaymentCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Cheques.
        /// </summary>
        internal static string PaymentCheck {
            get {
                return ResourceManager.GetString("PaymentCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compromisos de Pago.
        /// </summary>
        internal static string PaymentCommitments {
            get {
                return ResourceManager.GetString("PaymentCommitments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos.
        /// </summary>
        internal static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos por Cobrador.
        /// </summary>
        internal static string PaymentsToCollector {
            get {
                return ResourceManager.GetString("PaymentsToCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos a Operador.
        /// </summary>
        internal static string PaymentsToOperator {
            get {
                return ResourceManager.GetString("PaymentsToOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total del Pago.
        /// </summary>
        internal static string PaymentTotal {
            get {
                return ResourceManager.GetString("PaymentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente por Eliminar.
        /// </summary>
        internal static string PendingDelete {
            get {
                return ResourceManager.GetString("PendingDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente por Ingresar.
        /// </summary>
        internal static string PendingEntry {
            get {
                return ResourceManager.GetString("PendingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas Gestionadas.
        /// </summary>
        internal static string PeopleManaged {
            get {
                return ResourceManager.GetString("PeopleManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a %.
        /// </summary>
        internal static string Perc {
            get {
                return ResourceManager.GetString("Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % de Metas Establecidas.
        /// </summary>
        internal static string PercGoalSet {
            get {
                return ResourceManager.GetString("PercGoalSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestiones Realizadas.
        /// </summary>
        internal static string PerformedManagements {
            get {
                return ResourceManager.GetString("PerformedManagements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la Persona.
        /// </summary>
        internal static string PersonData {
            get {
                return ResourceManager.GetString("PersonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestiones por Persona.
        /// </summary>
        internal static string PersonManagements {
            get {
                return ResourceManager.GetString("PersonManagements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador de Telefonos.
        /// </summary>
        internal static string PhoneManager {
            get {
                return ResourceManager.GetString("PhoneManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfonos.
        /// </summary>
        internal static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor espere....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cartera.
        /// </summary>
        internal static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portugués.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Positivo.
        /// </summary>
        internal static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Positivas.
        /// </summary>
        internal static string Positives {
            get {
                return ResourceManager.GetString("Positives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privado.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Real.
        /// </summary>
        internal static string Real {
            get {
                return ResourceManager.GetString("Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Recibido.
        /// </summary>
        internal static string ReceivedMail {
            get {
                return ResourceManager.GetString("ReceivedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabación.
        /// </summary>
        internal static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restante.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restante(Local).
        /// </summary>
        internal static string RemainingLocal {
            get {
                return ResourceManager.GetString("RemainingLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restante(USD).
        /// </summary>
        internal static string RemainingUSD {
            get {
                return ResourceManager.GetString("RemainingUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordatorio.
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordatorios.
        /// </summary>
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder.
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder a Todos.
        /// </summary>
        internal static string ReplyAll {
            get {
                return ResourceManager.GetString("ReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes para supervisores.
        /// </summary>
        internal static string ReportsForSupervisors {
            get {
                return ResourceManager.GetString("ReportsForSupervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revertir.
        /// </summary>
        internal static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rif.
        /// </summary>
        internal static string Rif {
            get {
                return ResourceManager.GetString("Rif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regla.
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterios de la Regla.
        /// </summary>
        internal static string RuleCriteria {
            get {
                return ResourceManager.GetString("RuleCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regla de Salida.
        /// </summary>
        internal static string RuleOut {
            get {
                return ResourceManager.GetString("RuleOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reglas.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reglas de Distribución.
        /// </summary>
        internal static string RulesOfDistribution {
            get {
                return ResourceManager.GetString("RulesOfDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Gestión.
        /// </summary>
        internal static string SaveManagement {
            get {
                return ResourceManager.GetString("SaveManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reglas de Selección de Cuentas.
        /// </summary>
        internal static string SelectionRulesOfAuditors {
            get {
                return ResourceManager.GetString("SelectionRulesOfAuditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Correo.
        /// </summary>
        internal static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Enviado.
        /// </summary>
        internal static string SentMail {
            get {
                return ResourceManager.GetString("SentMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Severidad.
        /// </summary>
        internal static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal Bajo Supervisión.
        /// </summary>
        internal static string StaffUnderSupervision {
            get {
                return ResourceManager.GetString("StaffUnderSupervision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso.
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1: Seleccione un Nombre para su Campaña.
        /// </summary>
        internal static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 10: Indique una Regla de salida para La campaña.
        /// </summary>
        internal static string Step10 {
            get {
                return ResourceManager.GetString("Step10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 2: Seleccione las fechas para su campaña.
        /// </summary>
        internal static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3: Seleccione la Regla para la selección de cuentas.
        /// </summary>
        internal static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 4: Seleccione Los Operadores que van a gestionar estas cuentas.
        /// </summary>
        internal static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 5: Seleccione La forma en que va a distribuir las cuentas entre estos operadores.
        /// </summary>
        internal static string Step5 {
            get {
                return ResourceManager.GetString("Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 6: Seleccione el flujo de cobranzas a aplicar a estas cuentas y el paso inicial de ese flujo.
        /// </summary>
        internal static string Step6 {
            get {
                return ResourceManager.GetString("Step6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 7: Verifique la distribución de cuentas entre los operadores.
        /// </summary>
        internal static string Step7 {
            get {
                return ResourceManager.GetString("Step7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 8: Establezca un Monto como meta de cobranzas.
        /// </summary>
        internal static string Step8 {
            get {
                return ResourceManager.GetString("Step8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 9: Indique el Tipo de Asignación de las cuentas Libres de la Campaña.
        /// </summary>
        internal static string Step9 {
            get {
                return ResourceManager.GetString("Step9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisando.
        /// </summary>
        internal static string Supervising {
            get {
                return ResourceManager.GetString("Supervising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisión.
        /// </summary>
        internal static string Supervision {
            get {
                return ResourceManager.GetString("Supervision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor.
        /// </summary>
        internal static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suplantando.
        /// </summary>
        internal static string Supplanting {
            get {
                return ResourceManager.GetString("Supplanting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entradas y Salidas del Sistema.
        /// </summary>
        internal static string SystemInputsAndOutputs {
            get {
                return ResourceManager.GetString("SystemInputsAndOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Meta.
        /// </summary>
        internal static string TargetAmount {
            get {
                return ResourceManager.GetString("TargetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección Fiscal.
        /// </summary>
        internal static string TaxAddress {
            get {
                return ResourceManager.GetString("TaxAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantillas.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo Gestionando.
        /// </summary>
        internal static string Time_Managements {
            get {
                return ResourceManager.GetString("Time_Managements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        internal static string titLogin {
            get {
                return ResourceManager.GetString("titLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de Cobranzas - Veconinter.
        /// </summary>
        internal static string titSystem {
            get {
                return ResourceManager.GetString("titSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Totales.
        /// </summary>
        internal static string TotalAccounts {
            get {
                return ResourceManager.GetString("TotalAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total(Local).
        /// </summary>
        internal static string TotalLocal {
            get {
                return ResourceManager.GetString("TotalLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Totales.
        /// </summary>
        internal static string Totals {
            get {
                return ResourceManager.GetString("Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total(USD).
        /// </summary>
        internal static string TotalUSD {
            get {
                return ResourceManager.GetString("TotalUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferencia.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Asignación:.
        /// </summary>
        internal static string TypeOfAssignment {
            get {
                return ResourceManager.GetString("TypeOfAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Reporte.
        /// </summary>
        internal static string TypeOfReport {
            get {
                return ResourceManager.GetString("TypeOfReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Sin Asignar.
        /// </summary>
        internal static string UnassignedAccounts {
            get {
                return ResourceManager.GetString("UnassignedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo sin Clasificar.
        /// </summary>
        internal static string UnclassifiedMail {
            get {
                return ResourceManager.GetString("UnclassifiedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar contraseña de Correo.
        /// </summary>
        internal static string UpdateMailPassword {
            get {
                return ResourceManager.GetString("UpdateMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flujos de Trabajo.
        /// </summary>
        internal static string Workflows {
            get {
                return ResourceManager.GetString("Workflows", resourceCulture);
            }
        }
    }
}
