//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobranzas.ServicioSupervision {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSupervision.ISupervisionService")]
    public interface ISupervisionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupervisionService/OperadoresSupervisadosConSupervisor_lst", ReplyAction="http://tempuri.org/ISupervisionService/OperadoresSupervisadosConSupervisor_lstRes" +
            "ponse")]
        Cobranzas.OT.otOperadoresSimple[] OperadoresSupervisadosConSupervisor_lst(int idOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupervisionService/OperadoresSupervisados_lst", ReplyAction="http://tempuri.org/ISupervisionService/OperadoresSupervisados_lstResponse")]
        Cobranzas.OT.otOperadoresSimple[] OperadoresSupervisados_lst(int idOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupervisionService/OperadoresSupervisadosCompleto_lst", ReplyAction="http://tempuri.org/ISupervisionService/OperadoresSupervisadosCompleto_lstResponse" +
            "")]
        Cobranzas.OT.otOperadores[] OperadoresSupervisadosCompleto_lst(int idOperador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISupervisionServiceChannel : Cobranzas.ServicioSupervision.ISupervisionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupervisionServiceClient : System.ServiceModel.ClientBase<Cobranzas.ServicioSupervision.ISupervisionService>, Cobranzas.ServicioSupervision.ISupervisionService {
        
        public SupervisionServiceClient() {
        }
        
        public SupervisionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupervisionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupervisionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupervisionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cobranzas.OT.otOperadoresSimple[] OperadoresSupervisadosConSupervisor_lst(int idOperador) {
            return base.Channel.OperadoresSupervisadosConSupervisor_lst(idOperador);
        }
        
        public Cobranzas.OT.otOperadoresSimple[] OperadoresSupervisados_lst(int idOperador) {
            return base.Channel.OperadoresSupervisados_lst(idOperador);
        }
        
        public Cobranzas.OT.otOperadores[] OperadoresSupervisadosCompleto_lst(int idOperador) {
            return base.Channel.OperadoresSupervisadosCompleto_lst(idOperador);
        }
    }
}
